name: CI

on:
    push:
        branches:
            - main
    # Manual triggers
    workflow_dispatch:
      inputs:
        git-ref:
          description: Git Ref (Optional)
          required: false
        dry-run:
          description: Creates a draft release
          required: false

jobs:
   name: Build app
   runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
            npm install
            npm i react-native@0.64.1
            npm update "react-native"

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
            java-version: 1.8

      - name: Cache Gradle Wrapper
        uses: actions/cache@v2
        with:
            path: ~/.gradle/wrapper
            key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Cache Gradle Dependencies
        uses: actions/cache@v2
        with:
            path: ~/.gradle/caches
            key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
            restore-keys: |
                ${{ runner.os }}-gradle-caches-

      - name: Make Gradlew Executable
        run: cd android && chmod +x ./gradlew

      - name: Build Android Release
        run: |
            cd android && ./gradlew assembleRelease --no-daemon

      - name: Create Release
        uses: actions/upload-artifact@v2
        with:
          name: openreader
          path: android/app/build/outputs/apk/release

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: openreader
